"""Separate Progress and User tables

Revision ID: 7948fbc9ebfa
Revises: d9d673e3595f
Create Date: 2024-05-19 22:15:19.369687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7948fbc9ebfa'
down_revision: Union[str, None] = 'd9d673e3595f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
