"""Progress columns added

Revision ID: cb192ff2e151
Revises: 15682a305f1d
Create Date: 2024-05-14 14:25:08.534771

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb192ff2e151'
down_revision: Union[str, None] = '15682a305f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('words_learned_en', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_learned_fr', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_learned_it', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'words_learned_it')
    op.drop_column('users', 'words_learned_fr')
    op.drop_column('users', 'words_learned_en')
    # ### end Alembic commands ###
