"""ROUGH FINAL SCHEMA

Revision ID: f3cca0dc448d
Revises: 7948fbc9ebfa
Create Date: 2024-05-24 17:23:56.068116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cca0dc448d'
down_revision: Union[str, None] = '7948fbc9ebfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('words', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('progress')
    op.add_column('users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('users', sa.Column('words_learned_en', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_learned_fr', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_learned_it', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'words_learned_it')
    op.drop_column('users', 'words_learned_fr')
    op.drop_column('users', 'words_learned_en')
    op.drop_column('users', 'id')
    op.create_table('progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('words_learned_en', sa.INTEGER(), nullable=True),
    sa.Column('words_learned_fr', sa.INTEGER(), nullable=True),
    sa.Column('words_learned_it', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_info')
    op.drop_table('notes')
    # ### end Alembic commands ###
